project_id = "ehzqsfinrrdvcnlvaarx"

[functions.get-weather]
verify_jwt = false

[functions.generate-outfit-recommendation]
verify_jwt = true

[functions.identify-garment]
verify_jwt = true

[functions.search-product-info]
verify_jwt = false

[functions.generate-virtual-tryon]
verify_jwt = true

[functions.recommend-washing-frequency]
verify_jwt = true