project_id = "udiheaprrtgegajidwqd"

[functions.get-weather]
verify_jwt = false

[functions.generate-outfit-recommendation]
verify_jwt = true

[functions.identify-garment]
verify_jwt = true

[functions.search-product-info]
verify_jwt = false

[functions.generate-virtual-tryon]
verify_jwt = true

[functions.recommend-washing-frequency]
verify_jwt = true

[functions.generate-outfit-image]
verify_jwt = true

[functions.remove-background]
verify_jwt = true

[functions.generate-fashion-trends]
verify_jwt = true

[functions.generate-outfit-suggestion]
verify_jwt = true

[functions.generate-ootd-plan]
verify_jwt = true

[functions.save-fashion-trends]
verify_jwt = true
